// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PruebaMarktAPI.Models;

public partial class categoria
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int idcategorias { get; set; }

    [Required]
    [StringLength(100)]
    public string nombre { get; set; }

    [InverseProperty("idcategoriaNavigation")]
    public virtual ICollection<producto> productos { get; set; } = new List<producto>();
}