// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PruebaMarktAPI.Models;

[Index("idcategoria", Name = "idcategorias_idx")]
public partial class producto
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int idproductos { get; set; }

    [Required]
    [StringLength(45)]
    public string nombre { get; set; }

    [StringLength(100)]
    public string descripcion { get; set; }

    [Precision(2, 1)]
    public decimal? valoracion { get; set; }

    [Column(TypeName = "int(11)")]
    public int? idcategoria { get; set; }

    [ForeignKey("idcategoria")]
    [InverseProperty("productos")]
    public virtual categoria idcategoriaNavigation { get; set; }

    [InverseProperty("idproductoNavigation")]
    public virtual ICollection<venta> venta { get; set; } = new List<venta>();
}