// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PruebaMarktAPI.Models;

[Index("idproducto", Name = "fk-idproducto_idx")]
public partial class venta
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int idventas { get; set; }

    [Column(TypeName = "int(11)")]
    public int idproducto { get; set; }

    [Column(TypeName = "int(11)")]
    public int cantidad { get; set; }

    [Required]
    [StringLength(100)]
    public string nombreuser { get; set; }

    [ForeignKey("idproducto")]
    [InverseProperty("venta")]
    public virtual producto idproductoNavigation { get; set; }
}